# Configures whether/how players can open the compression workbench by
# interacting with a block, while optionally holding a "key" item to enable the
# interaction.
#
# For example, if set to `target: minecraft:fletching_table` and
# `holding: minecraft:diamond` then players with the correct permissions will be
# able to open the crafting workbench by right clicking a diamond against a
# fletching table.
open-on-interact:
  # Whether opening the crafting workbench by interacting with a block is
  # enabled.
  #
  # Values: true|false
  enabled: true
  # ID of the target block that must be interacted with (right clicked on) to
  # open the crafting workbench.
  #
  # Values: <any valid block id>
  target:  minecraft:fletching_table
  # ID of the item that must be held by the player when interacting with
  # (right clicking) the target block.
  #
  # To disable an item requirement, set to `minecraft:air`.
  #
  # Values: <any valid item id>
  holding: minecraft:diamond