name: block-compression
version: 1.5.3
author: Elizabeth Harper <foxcapades.io@gmail.com>
main: io.foxcapades.spigot.block.compression.BlockCompressionPlugin
website: https://github.com/Foxcapades/Spigot-Compression-Plugin
api-version: 1.17

commands:
  compress:
    id: bcp-compress
    description: Open the item compression UI.
    usage: /compress
    aliases:
      - zip
    permission: block-compression.gui.command
    permission-message: You do not have permission to use this command.
  bcgive:
    id: bcp-give
    description: Gives a user a compressed item at the specified level.
    usage: /bcgive <user> <item> <lvl> <qty>
    permission: block-compression.give
    permission-message: You do not have permission to use this command.
  bcreload:
    id: bcp-reload
    description: Reloads the allowed compressible items/blocks configs.
    usage: /bcreload
    permission: block-compression.reload
    permission-message: You do not have permission to use this command.

permissions:
  block-compression.gui:
    description: Grants access to to open the compression UI
    default: op
    children:
      block-compression.gui.command: true
      block-compression.gui.block: true
  block-compression.give:
    description: Grants access to the /bcgive command.
    default: op
  block-compression.reload:
    description: Grants access to the /bcreload command.
    default: op
