name: block-compression
version: 1.0-SNAPSHOT
author: Elizabeth Harper <foxcapades.io@gmail.com>
main: io.foxcapades.spigot.block.compression.BlockCompressionPlugin
website: https://github.com/Foxcapades
api-version: 1.17

commands:
  compress:
    # DO NOT CHANGE THIS
    # This value is used to map custom command overrides to their real purpose.
    # If this value is changed, the plugin will not be able to correctly
    # its commands.
    id: bcp-compress
    description: Open the item compression UI.
    usage: /<command>
    aliases:
      - zip
#    permission: block-compression.gui
#    permission-message: You do not have permission to compress blocks.

