name: block-compression
version: 1.1.0
author: Elizabeth Harper <foxcapades.io@gmail.com>
main: io.foxcapades.spigot.block.compression.BlockCompressionPlugin
website: https://github.com/Foxcapades/Spigot-Compression-Plugin
api-version: 1.17

commands:
  compress:
    id: bcp-compress
    description: Open the item compression UI.
    usage: /<command>
    aliases:
      - zip
    permission: block-compression.gui
    permission-message: You do not have permission to use this command.
  bcgive:
    id: bcp-give
    description: Gives a user a compressed item at the specified level.
    usage: /command <user> <item> <lvl> <qty>
    permission: block-compression.give
    permission-message: You do not have permission to use this command.
