name: block-compression
version: 2.0.0-SNAPSHOT
author: Elizabeth Harper <foxcapades.io@gmail.com>
main: io.foxcapades.spigot.block.compression.BlockCompressionPlugin
website: https://github.com/Foxcapades/Spigot-Compression-Plugin
api-version: 1.20

commands:
  bcgive:
    id: bcp-give
    description: Gives a user a compressed item at the specified level.
    usage: /bcgive <user> <item> <lvl> <qty>
    permission: block-compression.give
    permission-message: You do not have permission to use this command.
  bcreload:
    id: bcp-reload
    description: Reloads the allowed compressible items/blocks configs.
    usage: /bcreload
    permission: block-compression.reload
    permission-message: You do not have permission to use this command.

permissions:
  block-compression.tool:
    description: Grants access to the block compression tool.
    default: op
  block-compression.give:
    description: Grants access to the /bcgive command.
    default: op
  block-compression.reload:
    description: Grants access to the /bcreload command.
    default: op
