name: StackZip
version: 2.0.0-SNAPSHOT
main: io.foxcapades.bukkit.szip.StackZip
api-version: '1.21'

author: Elizabeth Harper <foxcapades.io@gmail.com>
website: https://github.com/Foxcapades/Spigot-Compression-Plugin

depend:
- ProtocolLib

commands:
  sz:
    id: sz
    aliases:
    - szip
    description: Block Compression commands.
    usage: /sz <subcommand> [options...]
    permission-message: You do not have permission to use this command.
  compress:
    id: sz-compress
    description: Open stack compression GUI
    aliases:
    - cmp
    - zip
    usage: /compress
    permission: szip.cmd.compress

default-permission: false

permissions:
  szip.*:
    description: Grants access to all StackZip permissions.
    default: false
    children:
    - szip.item.*
    - szip.cmd.*

  #
  # ITEM PERMISSIONS
  #

  szip.item.*:
    description: Grants access to all StackZip item permissions.
    default: op
    children:
    - szip.item.tool.*

  szip.item.tool.*:
    description: Grants access to craft and use the stack compression tool.
    default: op
    children:
    - szip.item.tool.craft
    - szip.item.tool.use

  szip.item.tool.craft:
    description: Grants access to craft but not use the stack compression tool.
    default: op

  szip.item.tool.use:
    description: Grants access to use but not craft the stack compression tool.
    default: not op

  #
  # COMMAND PERMISSIONS
  #

  szip.cmd.*:
    description: Grants access to the stack compression tool.
    default: false
    children:
    - szip.cmd.compress
    - szip.cmd.give
    - szip.cmd.reload

  szip.cmd.compress:
    description: Grants access to the '/sz compress' and '/compress' commands.
    default: op

  szip.cmd.give:
    description: Grants access to the '/sz give' command.
    default: op

  szip.cmd.reload:
    description: Grants access to the '/sz reload' command.
    default: false
