name: block-compression
version: 1.0.2
author: Elizabeth Harper <foxcapades.io@gmail.com>
main: io.foxcapades.spigot.block.compression.BlockCompressionPlugin
website: https://github.com/Foxcapades/Spigot-Compression-Plugin
api-version: 1.18

commands:
  compress:
    id: bcp-compress
    description: Open the item compression UI.
    usage: /<command>
    aliases:
      - zip
    permission: block-compression.gui
    permission-message: You do not have permission to compress blocks.

