package io.foxcapades.bukkit.inventory.meta

object MetaKey {
  const val MetaType = "meta"

  const val Amplifier          = "amplifier"
  const val AttributeModifiers = "attr-mods"
  const val Author             = "author"
  const val BaseType        = "base-type"
  const val Color           = "color"
  const val CustomModelData = "x-model-data"
  const val Damage          = "damage"
  const val DisplayName     = "display-name"
  const val Effect          = "effect"
  const val Effects         = "effects"
  const val Enchantments    = "enchantments"
  const val Entity          = "entity"
  const val FireResistant   = "resist-fire"
  const val Food            = "food"
  const val Generation      = "generation"
  const val GlintOverride   = "glint-override"
  const val HideTooltip     = "hide-tooltip"
  const val Instrument      = "instrument"
  const val Items           = "items"
  const val ItemFlags       = "item-flags"
  const val ItemName        = "item-name"
  const val JukeboxPlayable = "jukebox-playable"
  const val Lodestone       = "lodestone"
  const val Lore            = "lore"
  const val MapView         = "map-view"
  const val MaxDamage       = "max-damage"
  const val MaxStackSize    = "max-stack-size"
  const val Owner           = "owner"
  const val Pages           = "pages"
  const val Power           = "power"
  const val Profile         = "profile"
  const val Projectiles     = "projectiles"
  const val Rarity          = "rarity"
  const val Recipes         = "recipes"
  const val RepairCost      = "repair-cost"
  const val Sound           = "sound"
  const val Title           = "title"
  const val Tool            = "tool"
  const val Trim            = "trim"
  const val Unbreakable     = "unbreakable"
  const val Variant         = "variant"
}
